<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_FastOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * @var \Magento\Downloadable\Block\Catalog\Product\Links $block
 */
?>
<?php 
    $_linksPurchasedSeparately = $block->getLinksPurchasedSeparately();
    $sortOrder = $block->getSortOrder();
?>
<?php if ($block->getProduct()->isSaleable() && $block->hasLinks()):?>
    <?php $_links = $block->getLinks(); ?>
    <?php $_linksLength = 0; ?>
    <?php $_isRequired = $block->getLinkSelectionRequired(); ?>
    <!-- <legend class="legend links-title"><span><?php /* @escapeNotVerified */ echo $block->getLinksTitle() ?></span></legend><br> -->
    <div class="field downloads<?php if ($_isRequired) echo ' required' ?><?php if (!$_linksPurchasedSeparately) echo ' downloads-no-separately' ?>">
        <label class="label bss-required-label"><span><?php /* @escapeNotVerified */ echo $block->getLinksTitle() ?></span></label>
        <div class="control" id="bss-fastorder-downloadable-links-list" data-container-for="downloadable-links">
            <?php foreach ($_links as $_link): ?>
                <?php $_linksLength++;?>
                <div class="field choice" data-role="link">
                    <?php if ($_linksPurchasedSeparately): ?>
                        <input type="checkbox"
                               name="bss_fastorder_links[<?php echo $sortOrder;?>][]"
                               id="bss_fastorder_links_<?php /* @escapeNotVerified */ echo $_link->getId() ?>"
                               value="<?php /* @escapeNotVerified */ echo $_link->getId(); ?>" <?php /* @escapeNotVerified */ echo $block->getLinkCheckedValue($_link); ?> />
                        <input type="hidden" class="bss-attribute-select" name="bss_fastorder_links[<?php echo $sortOrder;?>][]" value="">
                    <?php endif; ?>
                    <label class="label" for="bss_fastorder_links_<?php /* @escapeNotVerified */ echo $_link->getId() ?>">
                        <span><?php echo $block->escapeHtml($_link->getTitle()); ?></span>
                        <?php if ($_link->getSampleFile() || $_link->getSampleUrl()): ?>
                            <a class="sample link"
                               href="<?php /* @escapeNotVerified */ echo $block->getLinkSampleUrl($_link) ?>" <?php echo $block->getIsOpenInNewWindow() ? 'target="_blank"' : ''; ?>>
                                <?php /* @escapeNotVerified */ echo __('sample') ?>
                            </a>
                        <?php endif; ?>
                        <?php if ($_linksPurchasedSeparately): ?>
                            <?php /* @escapeNotVerified */ echo $block->getLinkPrice($_link); ?>
                        <?php endif; ?>
                    </label>
                </div>
            <?php endforeach; ?>
            <?php if ($_linksPurchasedSeparately && $_linksLength > 1): ?>
                <div class="field choice downloads-all">
                    <input type="checkbox"
                           data-notchecked="<?php /* @escapeNotVerified */ echo __('Select all')?>"
                           data-checked="<?php /* @escapeNotVerified */ echo __('Unselect all')?>"
                           id="bss-fastorder-bss_fastorder_links_all" />
                    <label class="label" for="bss-fastorder-bss_fastorder_links_all"><span><?php /* @escapeNotVerified */ echo __('Select all')?></span></label>
                </div>
            <?php endif; ?>
        </div>
        <?php if ($_isRequired): ?>
            <span id="bss-links-advice-container">
                <div generated="true" class="bss-mage-error" style="display: block;">
                    <?php /* @escapeNotVerified */ echo __('Please select one of the options.'); ?>
                </div>
            </span>
        <?php endif;?>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
    "*":
        {
            "Bss_FastOrder/js/custom/downloadable": {
                "bssconfig":<?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>,
                "sortOrder":<?php /* @escapeNotVerified */ echo $sortOrder ?>,
                "defaultPrice": "<?php echo $block->getProduct()->getFinalPrice()?>"
            }
        }
    }
</script>
