<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_FastOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/** @var Bss\FastOrder\Block\FastOrderLink $block */
?>
<li class="nav item mini-fast-order">
    <a <?php if (!$block->getEnableMini()): ?> href="<?= $block->getUrlFastOrder() ?>" <?php endif; ?> >
        <?= __('Fast Order') ?>
    </a>
</li>
<ul class="mini-fast-order-toggle <?= $block->checkUrlFastOrder() ?>"></ul>

<?php if ($block->getEnableMini()) : ?>
<script type="text/x-magento-init">
        {
        "*": {
            "Bss_FastOrder/js/toggle-mini-fast-order": {}
            }
        }

</script>
<?php endif; ?>
