<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/** @var $block Bss\QuoteExtension\Block\Adminhtml\QuoteExtension\Edit\Info */
?>

<?php if (!$block->getQuote()->getIsVirtual()) : ?>
    <div class="admin__page-section-item quote-shipping-address">
        <?php /* Shipping Address */ ?>
        <div class="admin__page-section-item-title">
            <span class="title"><?php echo __('Shipping Address') ?></span>
        </div>
        <?php if ($block->getFormattedAddress('shipping')) : ?>
            <address class="admin__page-section-item-content">
                <?php echo $block->getFormattedAddress('shipping'); ?>
            </address>
        <?php else : ?>
            <address class="admin__page-section-item-content">
                <?php echo __('No Shipping Address!'); ?>
            </address>
        <?php endif ?>
    </div>
<?php endif; ?>