<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var $block \Bss\QuoteExtension\Block\QuoteExtension\View\Info */
?>
<?php // @codingStandardsIgnoreFile ?>

<?php
$helper = $block->getHelperStatus();
$quote = $block->getRequestQuote();
?>
<span class="order-status quote-status-<?= $block->escapeHtmlAttr($quote->getStatus()); ?>"><?= /* @escapeNotVerified */
    $block->escapeHtml($helper->getStatusLabel($quote->getStatus())); ?></span>
