<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ConfiguableGridView
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
/**
 * @var \Bss\ConfiguableGridView\Block\Product\View\Configurable $block
 */
?>
<script type="text/x-magento-template" id="tier-prices-template">
    <ul class="prices-tier items">
        <% var price=0 %>
        <% _.each(tierPrices, function(item, key) {
        if(price==0 || item.price<=price) {
        price=item.price;
        %>
        <%  var priceStr = '<span class="price-container price-tier_price">'
                + '<span data-price-amount="' + priceUtils.formatPrice(item.price, currencyFormat) + '"'
                + ' data-price-type=""' + ' class="price-wrapper ">'
                + '<span class="price">' + priceUtils.formatPrice(item.price, currencyFormat) + '</span>'
                + '</span>'
            + '</span>'; %>
        <li class="item">
            <%= '<?= $block->escapeHtml(__('Buy %1 for %2 each and', '%1', '%2')) ?>'
            .replace('%1', item.qty)
            .replace('%2', priceStr) %>
            <strong class="benefit">
                <?= $block->escapeHtml(__('save')) ?><span
                        class="percent tier-<%= key %>">&nbsp;<%= item.percentage %></span>%
            </strong>
        </li>

        <% } });
        %>
    </ul>
</script>
<div data-role="tier-price-block"></div>
