<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_FastOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * @var \Magento\Catalog\Block\Product\View\Options $block
 */
?>
<?php $_options = $block->decorateArray($block->getOptions()) ?>
<?php if (!empty($_options)): ?>
    <?php foreach ($_options as $_option): ?>
        <?php echo $block->getOptionHtml($_option) ?>
    <?php endforeach; ?>
<?php endif; ?>
<script type="text/x-magento-init">
    {
    "*":
        {
            "Bss_FastOrder/js/product/view/option": {
                "optionConfig": <?php /* @escapeNotVerified */ echo $block->getJsonConfig(); ?>

            }
        }
    }
</script>
