<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Bss\QuoteExtension\Block\Adminhtml\QuoteExtension\Edit\Items\Grid
 */
?>

<?php $_items = $block->getItems() ?>
<section id="order-items" class="admin__page-section quote-items" data-mage-init='{"loader": {}}'>
    <div class="admin__page-section-title">
        <strong class="title"><?= /* @escapeNotVerified */ $block->getHeaderText() ?></strong>
    </div>
    <?= $block->getButtonsHtml() ?>
    <?php if (empty($_items)): ?>
        <div id="order-items_grid">
            <div class="admin__table-wrapper">
                <table class="data-table admin__table-primary order-tables">
                    <thead>
                    <tr class="headings">
                        <th class="col-product"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
                        <th class="col-price"><span><?= /* @escapeNotVerified */ __('Price') ?></span></th>
                        <th class="col-qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                        <th class="col-subtotal"><span><?= /* @escapeNotVerified */ __('Subtotal') ?></span></th>
                        <th class="col-discount"><span><?= /* @escapeNotVerified */ __('Discount') ?></span></th>
                        <th class="col-row-total"><span><?= /* @escapeNotVerified */ __('Row Subtotal') ?></span></th>
                        <th class="col-action"><span><?= /* @escapeNotVerified */ __('Action') ?></span></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr class="even">
                        <td class="empty-text" colspan="100"><?= /* @escapeNotVerified */ __('No ordered items') ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    <?php else: ?>
        <div class="admin__table-wrapper" id="order-items_grid">
            <table class="data-table admin__table-primary order-tables">
                <thead>
                <tr class="headings">
                    <th class="col-product"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
                    <th class="col-price"><span><?= /* @escapeNotVerified */ __('Price') ?></span></th>
                    <th class="col-qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                    <th class="col-subtotal"><span><?= /* @escapeNotVerified */ __('Subtotal') ?></span></th>
                    <th class="col-discount"><span><?= /* @escapeNotVerified */ __('Discount') ?></span></th>
                    <th class="col-row-total"><span><?= /* @escapeNotVerified */ __('Row Subtotal') ?></span></th>
                    <th class="col-action"><span><?= /* @escapeNotVerified */ __('Action') ?></span></th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <td class="col-total"><?= /* @escapeNotVerified */ __('Total %1 product(s)', count($_items)) ?></td>
                    <td colspan="2" class="col-subtotal"><?= /* @escapeNotVerified */ __('Subtotal:') ?></td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($block->getSubtotal()) ?></strong></td>
                    <td class="col-price"><strong><?= /* @escapeNotVerified */ $block->formatPrice($block->getDiscountAmount()) ?></strong></td>
                    <td class="col-price">
                        <strong>
                            <?php
                            /* @escapeNotVerified */ echo $block->formatPrice($block->getSubtotalWithDiscount());
                            ?>
                        </strong>
                    </td>
                    <td colspan="2">&nbsp;</td>
                </tr>
                </tfoot>
                <?php $i = 0 ?>
                <?php foreach ($_items as $_item):$i++ ?>
                    <tbody class="<?= /* @escapeNotVerified */ ($i%2) ? 'even' : 'odd' ?>">
                    <tr>
                        <td class="col-product">
                            <span id="order_item_<?= /* @escapeNotVerified */ $_item->getId() ?>_title"><?= $block->escapeHtml($_item->getName()) ?></span>
                            <div class="product-sku-block">
                                <span><?= /* @escapeNotVerified */ __('SKU') ?>:</span>
                                <?= implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))) ?>
                            </div>
                            <div class="product-comment-block">
                                <span><?= /* @escapeNotVerified */ __('Comment') ?>:</span>
                                <?= implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getCurrentCommentItemId()))) ?>
                            </div>
                            <div class="product-configure-block">
                                <?= $block->getConfigureButtonHtml($_item) ?>
                            </div>
                        </td>
                        <td class="col-price">
                            <?= $block->getItemUnitPriceHtml($_item) ?>
                            <?php if(!$block->getCanShowPrice($_item)): ?>
                                <span>(<?= $block->escapeHtml(__('Hide Price')); ?>)</span>
                            <?php endif; ?>
                            <?php $_isCustomPrice = $block->usedCustomPriceForItem($_item) ?>
                            <?php if ($_tier = $block->getTierHtml($_item)): ?>
                                <div id="item_tier_block_<?= /* @escapeNotVerified */ $_item->getId() ?>"<?php if ($_isCustomPrice): ?> style="display:none"<?php endif; ?>>
                                    <a href="#" onclick="$('item_tier_<?= /* @escapeNotVerified */ $_item->getId() ?>').toggle();return false;"><?= /* @escapeNotVerified */ __('Tier Pricing') ?></a>
                                    <div style="display:none" id="item_tier_<?= /* @escapeNotVerified */ $_item->getId() ?>"><?= /* @escapeNotVerified */ $_tier ?></div>
                                </div>
                            <?php endif; ?>
                            <?php if ($block->canApplyCustomPrice($_item)): ?>
                                <div class="custom-price-block">
                                    <input type="checkbox"
                                           class="admin__control-checkbox"
                                           id="item_use_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>"
                                        <?php if ($_isCustomPrice): ?> checked="checked"<?php endif; ?>
                                           onclick="order.toggleCustomPrice(this, 'item_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>', 'item_tier_block_<?= /* @escapeNotVerified */ $_item->getId() ?>');"/>
                                    <label
                                        class="normal admin__field-label"
                                        for="item_use_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>">
                                        <span><?= /* @escapeNotVerified */ __('Custom Price') ?>*</span></label>
                                </div>
                            <?php endif; ?>
                            <input id="item_custom_price_<?= /* @escapeNotVerified */ $_item->getId() ?>"
                                   name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][custom_price]"
                                   value="<?= /* @escapeNotVerified */ sprintf("%.2f", $block->getOriginalEditablePrice($_item)) ?>"
                                <?php if (!$_isCustomPrice): ?>
                                    style="display:none"
                                    disabled="disabled"
                                <?php endif; ?>
                                   class="input-text item-price admin__control-text"/>
                        </td>
                        <td class="col-qty">
                            <input name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][qty]"
                                   class="input-text item-qty admin__control-text"
                                   value="<?= /* @escapeNotVerified */ $_item->getQty()*1 ?>"
                                   maxlength="12" />
                        </td>
                        <td class="col-subtotal col-price">
                            <?= $block->getItemRowTotalHtml($_item) ?>
                        </td>
                        <td class="col-discount col-price">
                            <?= /* @escapeNotVerified */ $block->formatPrice(-$_item->getTotalDiscountAmount()) ?>
                            <div class="discount-price-block">
                                <input id="item_use_discount_<?= /* @escapeNotVerified */ $_item->getId() ?>"
                                       class="admin__control-checkbox"
                                       name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][use_discount]"
                                       <?php if (!$_item->getNoDiscount()): ?>checked="checked"<?php endif; ?>
                                       value="1"
                                       type="checkbox" />
                                <label
                                    for="item_use_discount_<?= /* @escapeNotVerified */ $_item->getId() ?>"
                                    class="normal admin__field-label">
                                    <span><?= /* @escapeNotVerified */ __('Apply') ?></span></label>
                            </div>

                        </td>
                        <td class="col-price col-row-subtotal">
                            <?= $block->getItemRowTotalWithDiscountHtml($_item) ?>
                        </td>
                        <td class="col-actions last">
                            <select class="admin__control-select" name="item[<?= /* @escapeNotVerified */ $_item->getId() ?>][action]">
                                <option value=""><?= /* @escapeNotVerified */ __('Please select') ?></option>
                                <option value="remove"><?= /* @escapeNotVerified */ __('Remove') ?></option>
                            </select>
                        </td>
                    </tr>

                    <?php $hasMessageError = false; ?>
                    <?php foreach ($_item->getMessage(false) as $messageError):?>
                        <?php if (!empty($messageError)) : ?>
                            <?php $hasMessageError = true ?>
                        <?php endif ?>
                    <?php endforeach; ?>

                    <?php if ($hasMessageError):?>
                        <tr class="row-messages-error">
                            <td colspan="100"> <!-- ToDo UI: remove the 100 -->
                                <?php foreach ($_item->getMessage(false) as $message):
                                    if (empty($message)) {
                                        continue;
                                    }
                                    ?>
                                    <div class="message <?php if ($_item->getHasError()): ?>message-error<?php else: ?>message-notice<?php endif; ?>">
                                        <?= $block->escapeHtml($message) ?>
                                    </div>
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    <?php endif;?>

                    <?= $block->getItemExtraInfo($_item)->toHtml() ?>
                    </tbody>
                <?php endforeach; ?>
                <input name="quote_id" class="hidden" type="hidden" value="<?= /* @escapeNotVerified */ $block->getQuote()->getId() ?>" />
                <input name="quote_manage_id" class="hidden" type="hidden" value="<?= /* @escapeNotVerified */ $block->getManageQuote()->getEntityId() ?>" />
                <input name="status" class="hidden" type="hidden" value="<?= /* @escapeNotVerified */ $block->getManageQuote()->getStatus() ?>" />
            </table>
            <p><small><?= /* @escapeNotVerified */ $block->getInclExclTaxMessage() ?></small></p>
        </div>
        <div class="order-discounts">
            <?= $block->getButtonHtml(__('Update Items and Quantities'), 'order.itemsUpdate()', 'action-secondary') ?>
        </div>

        <script>
            require([
                'Bss_QuoteExtension/js/quote/edit/form'
            ], function(){
                quote.itemsOnchangeBind()
            });
        </script>
    <?php endif; ?>
</section>


