<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_FastOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var \Bss\FastOrder\Block\Product\View\Options\Type\Date $block
 */
?>
<?php $_option = $block->getOption() ?>
<?php $_optionId = $_option->getId() ?>
<?php $class = ($_option->getIsRequire()) ? ' required' : ''; ?>
<div class="field date<?= /* @escapeNotVerified */ $class ?> bss-options-info"
     data-mage-init='{"priceOptionDate":{"fromSelector":"#product_addtocart_form"}}'>
    <fieldset class="fieldset fieldset-product-options-inner<?= /* @escapeNotVerified */ $class ?>">
        <legend class="legend">
            <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
            <?= /* @escapeNotVerified */ $block->getFormatedPrice() ?>
        </legend>
        <div class="control">
            <?php if ($_option->getType() == \Bss\FastOrder\Model\Product\Option::OPTION_TYPE_DATE_TIME ) { ?>
                <?= $block->getDateTimeHtml() ?>
                <?= $block->getTimeHtml() ?>
            <?php } elseif ($_option->getType() == \Bss\FastOrder\Model\Product\Option::OPTION_TYPE_DATE) { ?>
                <?= $block->getDateHtml() ?>
            <?php } elseif ($_option->getType() == \Bss\FastOrder\Model\Product\Option::OPTION_TYPE_TIME) { ?>
                <?= $block->getTimeHtml() ?>
            <?php } ?>
            <?php if ($_option->getIsRequire()): ?>
                <input type="hidden"
                       name="validate_datetime_<?= /* @escapeNotVerified */ $_optionId ?>"
                       class="validate-datetime-<?= /* @escapeNotVerified */ $_optionId ?>"
                       value=""
                       data-validate="{'validate-required-datetime':<?= /* @escapeNotVerified */ $_optionId ?>}"/>
            <?php else: ?>
                <input type="hidden"
                       name="validate_datetime_<?= /* @escapeNotVerified */ $_optionId ?>"
                       class="validate-datetime-<?= /* @escapeNotVerified */ $_optionId ?>"
                       value=""
                       data-validate="{'validate-optional-datetime':<?= /* @escapeNotVerified */ $_optionId ?>}"/>
            <?php endif; ?>
            <script type="text/x-magento-init">
            {
                "#product_addtocart_form": {
                    "validation": {
                        "ignore": ":hidden:not(input[name^='validate_datetime_'])"
                    }
                }
            }
        </script>
        </div>
    </fieldset>

</div>
