<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2023 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

$comments = $block->getComments();
?>
<?php if ($comments): ?>
    <table class="comment">
        <?php foreach ($comments as $comment): ?>
            <tr>
                <td><?= $comment?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
