<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomerAttributes
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile

use Bss\CustomerAttributes\Block\Frontend\Register\CustomerSectionAttribute;
use Bss\CustomerAttributes\Model\Config\Source\DisplayBackendCustomerDetail;
/** @var CustomerSectionAttribute $block */

?>
<?php $viewModel = $block->getViewModel();
?>

<?php if ($viewModel == null): ?>
    <?php $viewModel = $block; ?>
<?php endif; ?>
<?php $attributeHelper = $viewModel->getCustomerAttributeHelper(); ?>
<?php $b2BRegistrationIntegration = $viewModel->getB2BRegistrationIntegrationHelper(); ?>
<?php $attributeCollection = $attributeHelper->getUserDefinedAttributes(); ?>
<?php
$attributeCollectionData = $attributeCollection->getData();
$almostDependentArr = $viewModel->getListDependentAttributeCode($attributeCollectionData);
$notAvailableAttribute = $viewModel->getListDisableAttribute($attributeCollectionData);
$finalDependentArr = $viewModel->getListAttributeIdNotShow($attributeCollectionData);
?>
<?php

$customerAttrFromOrder = [];
$customerAttrFromOrder = $viewModel->getSession()->getCustomerAttributes();
if ($customerAttrFromOrder) {
    $viewModel->getSession()->unsCustomerAttributes();
}
$enableB2b = false;
if ($block->getModuleName() == "Bss_B2bRegistration") {
    $enableB2b = true;
}
?>
<?php $hasField = false; ?>
<?php if ($attributeCollection->getSize() > 0) : ?>
    <?php if ($enableB2b ? $block->isCustomerSectionAttribute() : $viewModel->isCustomerSectionAttribute()) : ?>
        <fieldset class="fieldset create info" id="info">
    <?php endif; ?>
    <!-- For all user defined attributes -->
    <?php $attributeValues = []; ?>
    <?php $displayValues = $viewModel->displayChildValues(); ?>
    <?php foreach ($attributeCollection as $attribute)
        :
        ?>
        <?php foreach ($block->getData() as $option):
        $attributeValues[] = [
            'value' => $viewModel->getDependentData($attribute->getData('attribute_id'))->getData()
        ];
        foreach ($attributeValues as $key => $value):
            if ($value['value'] == null || $value['value']['dependents_data'] == 'null') {
                unset($attributeValues[$key]);
            }
        endforeach;
    endforeach;
        ?>
    <?php if (!$enableB2b && $b2BRegistrationIntegration->getAttributeDisplay($attribute->getAttributeCode()) ==
        DisplayBackendCustomerDetail::B2B_ACCOUNTS): ?>
            <?php continue; ?>
    <?php endif; ?>
    <?php if ($enableB2b && $b2BRegistrationIntegration->getAttributeDisplay($attribute->getAttributeCode()) ==
        DisplayBackendCustomerDetail::NORMAL_ACCOUNTS): ?>
        <?php continue; ?>
    <?php endif; ?>
        <?php if ($block->isShowIn($attribute->getAttributeCode())) : ?>
        <!-- For all user defined attributes which are set for customer create account -->
        <?php
        if (isset($customerAttrFromOrder[$attribute->getAttributeCode()])) {
            $fromCheckout = true;
        } else {
            $fromCheckout = false;
        }
        if ($attributeHelper->isAttribureForCustomerAccountCreate($attribute->getAttributeCode())
            || $attributeHelper->isAttribureForB2BCustomerAccountCreate($attribute->getAttributeCode())
        ) {
            $show = true;
        } else {
            $show = false;
        }
        if ($viewModel->isEnableCustomerAttributeDependency()) {
            if (($fromCheckout && !$show)
                || (!empty($viewModel->getDependentData($attribute->getData('attribute_id'))->getData()))
                || $viewModel->getDependentData($attribute->getData('attribute_id'))->getData() === []
            ) {
                $hidden = false;
            } else {
                $hidden = true;
            }
        } else {
            $hidden = false;
        }
        ?>
        <?php if ($show || $fromCheckout): ?>
            <?php if (!$hasField && !$hidden && $block->isCustomerSectionAttribute()): ?>
                <?php $hasField = true; ?>
                <legend class="legend"><span><?php echo $attributeHelper->getTitle() ?></span></legend><br>
            <?php endif ?>
            <?php $frontEndLabel = $attribute->getStoreLabel($attributeHelper->getStoreId()); ?>
            <?php $getAttributeCodeFunction = "get" . str_replace(' ', '', ucwords(str_replace('_', ' ', $attribute->getAttributeCode()))); ?>
            <?php $fieldRequiredClass = ($attribute->getIsRequired()) ? 'data-validate="{required:true}"' : '' ?>
            <?php $fieldFrontendClass = ($attribute->getFrontendClass()) ? $attribute->getFrontendClass() : '' ?>
            <?php
            if ($customerAttrFromOrder && isset($customerAttrFromOrder[$attribute->getAttributeCode()])) {
                $fieldValue = $customerAttrFromOrder[$attribute->getAttributeCode()];
            } else {
                $fieldValue = ($block->getFormData()->getData($attribute->getAttributeCode()))
                    ? $block->getFormData()->getData($attribute->getAttributeCode()) : $attribute->getDefaultValue();
            }
            ?>
            <?php if ($attribute->getFrontendInput() == 'text'): ?>
                <div
                    class="field <?php echo $attribute->getAttributeCode(); ?> <?php if ($attribute->getIsRequired()): ?>required<?php endif; ?>"
                    id="<?php echo $attribute->getData('attribute_id'); ?>"
                >
                    <label for="<?php echo $attribute->getAttributeCode(); ?>"
                           class="label"><span><?php /* @escapeNotVerified */
                            echo __($frontEndLabel) ?></span></label>
                    <div class="control">
                        <input type="text" name="<?php echo $attribute->getAttributeCode(); ?>"
                               id="<?php echo $attribute->getAttributeCode(); ?>"
                               value="<?php echo $block->escapeHtml($fieldValue) ?>"
                               title="<?php echo __($frontEndLabel) ?>"
                               class="input-text <?php echo $fieldFrontendClass; ?>" <?php echo $fieldRequiredClass; ?>>
                    </div>
                </div>
            <?php elseif ($attribute->getFrontendInput() == 'textarea'): ?>
                <div
                    class="field <?php echo $attribute->getAttributeCode(); ?> <?php if ($attribute->getIsRequired()): ?>required<?php endif; ?>"
                    id="<?php echo $attribute->getData('attribute_id'); ?>"

                >
                    <label for="<?php echo $attribute->getAttributeCode(); ?>"
                           class="label"><span><?php /* @escapeNotVerified */
                            echo __($frontEndLabel) ?></span></label>
                    <div class="control">
                        <textarea class="textarea" cols="15" rows="2" title="<?php echo __($frontEndLabel); ?>"
                                  name="<?php echo $attribute->getAttributeCode(); ?>"
                                  id="<?php echo $attribute->getAttributeCode(); ?>" <?php echo $fieldRequiredClass; ?>><?php echo $block->escapeHtml($fieldValue); ?></textarea>
                    </div>
                </div>
            <?php elseif ($attribute->getFrontendInput() == 'date'): ?>
                <?php
                if ($fieldValue) {
                    $date = $attributeHelper->formatDate($fieldValue);
                } else {
                    $date = "";
                }
                ?>
                <div
                    class="field <?php echo $attribute->getAttributeCode(); ?> <?php if ($attribute->getIsRequired()): ?>required<?php endif; ?>"
                    id="<?php echo $attribute->getData('attribute_id'); ?>"

                >

                    <label for="<?php echo $attribute->getAttributeCode(); ?>"
                           class="label"><span><?php /* @escapeNotVerified */
                            echo __($frontEndLabel) ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" title="<?php echo __($frontEndLabel); ?>"
                               value="<?php echo $block->escapeHtml($date) ?>"
                               id="<?php echo $attribute->getAttributeCode(); ?>"
                               name="<?php echo $attribute->getAttributeCode(); ?>" <?php echo $fieldRequiredClass; ?>>
                        <script type="text/x-magento-init">
                                     {
                             "#<?php echo $attribute->getAttributeCode(); ?>": {
                                 "Bss_CustomerAttributes/js/date": {
                                 }
                             }
                         }





                        </script>
                    </div>
                </div>
            <?php elseif ($attribute->getFrontendInput() == 'boolean'): ?>
                <div
                    class="field <?php echo $attribute->getAttributeCode(); ?> <?php if ($attribute->getIsRequired()): ?>required<?php endif; ?>"
                    id="<?php echo $attribute->getData('attribute_id'); ?>"

                >
                    <label for="<?php echo $attribute->getAttributeCode(); ?>"
                           class="label"><span><?php /* @escapeNotVerified */
                            echo __($frontEndLabel) ?></span></label>
                    <div class="control">
                        <select id="<?php echo $attribute->getAttributeCode(); ?>"
                                name="<?php echo $attribute->getAttributeCode(); ?>"
                                title="<?php echo __($frontEndLabel); ?>" <?php echo $fieldRequiredClass; ?>>
                            <?php $options = $attributeHelper->getAttributeOptions($attribute->getAttributeCode()); ?>
                            <?php foreach ($options as $option): ?>
                                <option
                                    value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $fieldValue) {
                                    echo ' selected="selected"';
                                } ?>
                                    id="<?php echo $option['value']; ?>"
                                ><?php echo $option['label']->getText(); ?></option>

                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            <?php elseif ($attribute->getFrontendInput() == 'radio'): ?>
                <?php $fieldRequiredClass = ($attribute->getIsRequired()) ? 'data-validate="{\'validate-one-required-by-name\':true}"' : '' ?>
                <div
                    class="field <?php echo $attribute->getAttributeCode(); ?> <?php if ($attribute->getIsRequired()): ?>required<?php endif; ?>"
                    id="<?php echo $attribute->getData('attribute_id'); ?>"
                >
                    <label for="<?php echo $attribute->getAttributeCode(); ?>"
                           class="label"><span><?php /* @escapeNotVerified */
                            echo __($frontEndLabel) ?></span></label>
                    <div class="control">
                        <?php $options = $attributeHelper->getAttributeOptions($attribute->getAttributeCode()); ?>

                        <?php foreach ($options as $option): ?>
                            <?php if (!$option['value']) {
                                continue;
                            } ?>
                            <div class="field choice"
                                 id="<?php echo $option['value']; ?>">
                                <input type="radio"
                                       class="radio <?php echo $attribute->getAttributeCode() ?>"
                                       id="<?php echo $attribute->getAttributeCode() . $option['value']; ?>"
                                    <?php echo $fieldRequiredClass; ?>
                                       name="<?php echo $attribute->getAttributeCode(); ?>"
                                       data-selector="<?php echo $attribute->getAttributeCode(); ?>"
                                    <?php if ($option['value'] == $fieldValue) {
                                        echo ' checked="checked"';
                                    } ?>
                                       value="<?php echo $option['value'] ?>"/>
                                <label class="label"
                                       for="<?php echo $attribute->getAttributeCode() . $option['value']; ?>">
                                    <span><?php echo $option['label']; ?></span>
                                </label>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>

            <?php elseif ($attribute->getFrontendInput() == 'select') : ?>
                <div
                    class="field <?php echo $attribute->getAttributeCode(); ?> <?php if ($attribute->getIsRequired()): ?>required<?php endif; ?>"
                    id="<?php echo $attribute->getData('attribute_id'); ?>"

                >
                    <label for="<?php echo $attribute->getAttributeCode(); ?>"
                           class="label"><span><?php /* @escapeNotVerified */
                            echo __($frontEndLabel) ?></span></label>
                    <div class="control">
                        <select id="<?php echo $attribute->getAttributeCode(); ?>"
                                name="<?php echo $attribute->getAttributeCode(); ?>"
                                title="<?php echo __($frontEndLabel); ?>" <?php echo $fieldRequiredClass; ?>>
                            <?php $options = $attributeHelper->getAttributeOptions($attribute->getAttributeCode()); ?>
                            <?php foreach ($options as $option): ?>
                                <option
                                    value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $fieldValue) {
                                    echo ' selected="selected"';
                                }
                                ?> id="<?php echo $option['value']; ?>"><?php echo $option['label']; ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            <?php elseif ($attribute->getFrontendInput() == 'multiselect'): ?>
                <div
                    class="field <?php echo $attribute->getAttributeCode(); ?> <?php if ($attribute->getIsRequired()): ?>required<?php endif; ?>"
                    id="<?php echo $attribute->getData('attribute_id'); ?>"

                >
                    <label for="<?php echo $attribute->getAttributeCode(); ?>"
                           class="label"><span><?php /* @escapeNotVerified */
                            echo __($frontEndLabel) ?></span></label>
                    <div class="control">
                        <select multiple="multiple" size="5" id="<?php echo $attribute->getAttributeCode(); ?>"
                                name="<?php echo $attribute->getAttributeCode(); ?>[]"
                                title="<?php echo __($frontEndLabel); ?>"
                                class="multiselect" <?php echo $fieldRequiredClass; ?>>
                            <?php $options = $attributeHelper->getAttributeOptions($attribute->getAttributeCode()); ?>
                            <?php foreach ($options as $option): ?>
                                <?php $selectedOptions = is_array($fieldValue) ? $fieldValue : explode(',', $fieldValue); ?>
                                <?php if (!$option['value'] || !$option['label']) {
                                    continue;
                                } ?>
                                <option value="<?php echo $option['value'] ?>" id="<?php echo $option['value']; ?>"
                                    <?php if (in_array($option['value'], $selectedOptions)) {
                                        echo ' selected="selected"';
                                    } ?>
                                >
                                    <?php echo $option['label']; ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            <?php elseif ($attribute->getFrontendInput() == 'checkboxs') : ?>
                <?php $fieldRequiredClass = ($attribute->getIsRequired()) ? 'data-validate="{\'validate-one-required-by-name\':true}"' : '' ?>
                <div
                    class="field <?php echo $attribute->getAttributeCode(); ?> <?php if ($attribute->getIsRequired()): ?>required<?php endif; ?>"
                    id="<?php echo $attribute->getData('attribute_id'); ?>"

                >
                    <label for="<?php echo $attribute->getAttributeCode(); ?>"
                           class="label"><span><?php /* @escapeNotVerified */
                            echo __($frontEndLabel) ?></span></label>
                    <div class="control">
                        <?php $options = $attributeHelper->getAttributeOptions($attribute->getAttributeCode()); ?>
                        <?php foreach ($options as $option): ?>
                            <?php if (!$option['value']) {
                                continue;
                            } ?>
                            <?php $selectedOptions = is_array($fieldValue) ? $fieldValue : explode(',', $fieldValue); ?>
                            <div class="field choice" id="<?php echo $option['value']; ?>"
                                <?php if ($hidden) {
                                    echo ' hidden';
                                } ?>
                            >
                                <input type="checkbox"
                                       class="checkbox <?php echo $attribute->getAttributeCode() ?>"
                                       id="<?php echo $attribute->getAttributeCode() . $option['value']; ?>"
                                    <?php echo $fieldRequiredClass; ?>
                                       name="<?php echo $attribute->getAttributeCode(); ?>[]"
                                       data-selector="<?php echo $attribute->getAttributeCode(); ?>"
                                    <?php if (in_array($option['value'], $selectedOptions)) {
                                        echo ' checked="checked"';
                                    } ?>
                                       value="<?php echo $option['value'] ?>"/>
                                <label class="label"
                                       for="<?php echo $attribute->getAttributeCode() . $option['value']; ?>">
                                    <span><?php echo $option['label']; ?></span>
                                </label>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php elseif ($attribute->getFrontendInput() == 'file'): ?>
                <?php $fieldRequiredClass = ($attribute->getIsRequired()) ? 'data-validate="{required:true}"' : '' ?>
                <div
                    class="field  <?php echo $attribute->getAttributeCode(); ?> <?php if ($attribute->getIsRequired()): ?>required<?php endif; ?>"
                    id="<?php echo $attribute->getData('attribute_id'); ?>"

                >
                    <label for="<?php echo $attribute->getAttributeCode(); ?>"
                           class="label"><span><?php /* @escapeNotVerified */
                            echo __($frontEndLabel) ?></span></label>
                    <div class="control">
                        <input type="file" id="<?php echo $attribute->getAttributeCode() ?>"
                               name="<?= /* @escapeNotVerified */
                               $attribute->getAttributeCode() ?>"
                               value="" <?php echo $fieldRequiredClass ?>
                               class="input-file <?php echo $attribute->getAttributeCode() . "size" ?> <?php echo $attribute->getAttributeCode() . "extension" ?>">
                        <?php $getDataCustomerAttributes = $attributeHelper->getDataCustomerAttributes($attribute); ?>
                        <script type="text/x-magento-init">
                            {
                            "#<?php echo $attribute->getAttributeCode(); ?>": {
                                "Bss_CustomerAttributes/js/file": {
                                "fileSize" : "<?= $getDataCustomerAttributes['fileSize'] ?>",
                                "fileExtension" : "<?= $getDataCustomerAttributes['fileExtension']; ?>",
                                "validatorSize" : "<?= $getDataCustomerAttributes['validatorSize']; ?>",
                                "validatorExtensions" : "<?= $getDataCustomerAttributes['validatorExtensions']; ?>",
                                "id" : "<?= $attribute->getAttributeCode(); ?>"
                                    }
                                }
                            }





                        </script>
                        <input type="hidden" id="<?php echo $attribute->getAttributeCode() ?>_value"
                               name="<?= /* @escapeNotVerified */
                               $attribute->getAttributeCode() ?>_value" value=""
                               <?php if ($attribute->getIsRequired()): ?>data-validate="{required:true}" <?php endif; ?>/>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php endforeach; ?>
    <?php if ($viewModel->isCustomerSectionAttribute()) : ?>
        </fieldset>
    <?php endif; ?>
<?php endif; ?>
<?php if (!isset($attributeValues) || $viewModel->isEnableCustomerAttributeDependency() == '0') {
    $attributeValues = [];
} else {
    $attributeValues = $viewModel->validateDependentAttributeInfo($attributeValues, $attributeCollectionData);
} ?>
<?php
$firstKey = array_key_first($attributeValues);
$lastKey = array_key_last($attributeValues);
for ($i = $firstKey; $i <= $lastKey - 1; $i++) {
    if (empty($attributeValues[$i])) {
        continue;
    }
    for ($j = $i + 1; $j <= $lastKey; $j++) {
        if (empty($attributeValues[$j])) {
            continue;
        }
        if (implode($attributeValues[$i]['value']) == implode($attributeValues[$j]['value'])) {
            unset($attributeValues[$j]);
        }
    }
}
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Bss_CustomerAttributes/js/dependent": {
            "attrValues" :"<?= $block->escapeJs($viewModel->encodeFunction($attributeValues)) ?>",
            "finalDependentArr" :"<?= $block->escapeJs($viewModel->encodeFunction($finalDependentArr)) ?>",
            "displayValues" :"0" <?php ?>
            }
        }
    }
</script>
