<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * @category   BSS
 * @package    Bss_MultiWishlist
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile

?>
<?php
/* @var $block Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Remove */
?>
<a href="#" class="move_to_wishlist" data-url="<?php echo $block->getUrl('multiwishlist/index/movetowishlist') ?>" data-role="move" data-post-move='<?php /* @escapeNotVerified */ echo $block->getItemRemoveParams($block->getItem()); ?>' title="<?php /* @escapeNotVerified */ echo __('Move Item') ?>" class="btn-move action move">
    <span><?php /* @escapeNotVerified */ echo __('Move');?></span>
</a>
