<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_FastOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * @var $block \Magento\Backend\Block\Widget\Grid\Serializer
 */
?>
<?php
// phpcs:ignore
$_id = 'id_' . hash('sha256', microtime(), false);
?>
<?php $formId = $block->getFormId()?>
<?php if (!empty($formId)) : ?>
    <script>
        require([
            'prototype',
            'mage/adminhtml/grid'
        ], function(){
            Event.observe(window, "load", function(){
                var serializeInput  = document.createElement('input');
                serializeInput.type = 'hidden';
                serializeInput.name = '<?= $block->escapeJs($block->getInputElementName()) ?>';
                serializeInput.id   = '<?= /* @noEscape */ $_id ?>';
                try {
                    document.getElementById('<?= $block->escapeJs($formId) ?>').appendChild(serializeInput);
                    new serializerController('<?= /* @noEscape */ $_id ?>', <?= /* @noEscape */ $block->getDataAsJSON() ?>, <?= /* @noEscape */ $block->getColumnInputNames(true) ?>, <?= $block->escapeJs($block->getGridBlock()->getJsObjectName()) ?>, '<?= $block->escapeJs($block->getReloadParamName()) ?>');
                } catch(e) {
                    //Error add serializer
                }
            });
        });
    </script>
<?php else :?>
    <input type="hidden" name="<?= $block->escapeHtmlAttr($block->getInputElementName()) ?>"  value="" id="<?= /* @noEscape */ $_id ?>" />
    <script>
        require([
            'jquery',
            'mage/adminhtml/grid'
        ], function($){
            var gridModel = new serializerController('<?= /* @noEscape */ $_id ?>', <?= /* @noEscape */ $block->getDataAsJSON() ?>, <?= /* @noEscape */ $block->getColumnInputNames(true) ?>, <?= $block->escapeJs($block->getGridBlock()->getJsObjectName()) ?>, '<?= $block->escapeJs($block->getReloadParamName()) ?>');
            $('#fastorder_prepopulated_product_product_selector-container #fastorder_prepopulated_product_product_selector').change(function () {
                var selectedNewValue = $(this).val().split(',');
                gridModel.grid.reloadParams['selected_products[]'] = selectedNewValue;
            })
        });
    </script>
<?php endif;?>
