<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CompanyAccount
 * @author     Extension Team
 * @copyright  Copyright (c) 2020-2023 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var $block Filter */

use Bss\CompanyAccount\Block\Report\Filter;

$compatibleQuoteExtension = $block->getCompatibleQuoteExtension();
$enableQuoteExtension = $compatibleQuoteExtension->isEnableQuoteExtension();
if ($enableQuoteExtension) {
    $users = $compatibleQuoteExtension->getSubUserQuote();
} else {
    $users = $block->getItems();
}
?>

<div id="bss-table-filter">
    <?php if (count($users)) : ?>
    <div class="table-wrapper">
        <table id="my-sub-user-table" class="data table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Sub-Users')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $block->escapeHtml(__('User #')) ?></th>
                <th scope="col" class="col name"><?= $block->escapeHtml(__('Name')) ?></th>
                <th scope="col" class="col email"><?= $block->escapeHtml(__('Email')) ?></th>
                <th scope="col" class="col total"><?= $block->escapeHtml(__('Total Order Value')) ?></th>
                <th scope="col" class="col number of orders"><?= $block->escapeHtml(__('Number of Orders')) ?></th>
                <?php if ($enableQuoteExtension) : ?>
                    <th scope="col" class="col number of orders"><?= $block->escapeHtml(__('Number of Quotes')) ?></th>
                <?php endif; ?>
                <th scope="col" class="col date"><?= $block->escapeHtml(__('Created Date')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var \Bss\CompanyAccount\Api\Data\SubUserOrderInterface|\Bss\CompanyAccount\Model\SubUser $user */ ?>
            <?php foreach ($users as $user) : ?>
                <tr>
                    <?php if ($enableQuoteExtension) :
                        $subName = $user->getSubName();
                        $subEmail = $user->getSubEmail();
                        $grandTotal = $user->getData('grand_total');
                        $numTotal = $user->getData('count');
                        if ($grandTotal == 0) {
                            $numTotal = 0;
                        }
                        ?>
                    <?php else :
                        $subName = $user->subUser()->getSubName();
                        $subEmail = $user->subUser()->getSubEmail();
                        $grandTotal = $user->getGrandTotal();
                        $numTotal =$user->getCount();
                        ?>
                    <?php endif; ?>
                    <td data-th="<?= $block->escapeHtmlAttr(__('User #')) ?>" class="col id">
                        <?= $block->escapeHtml($user->getSubId()) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Name')) ?>" class="col name">
                        <?= $block->escapeHtml($subName) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="col email">
                        <a href="mailto:<?= $block->escapeHtml($subEmail) ?>">
                            <?= $block->escapeHtml($subEmail) ?>
                        </a>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Total Order Value')) ?>" class="col total">
                        <?= $block->formatValue($grandTotal) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Number of Orders')) ?>" class="col number of orders">
                        <?= $block->escapeHtml($numTotal) ?>
                    </td>
                    <!--Display quantity of quote subUser-->
                    <?php if ($enableQuoteExtension) : ?>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Number of Orders')) ?>"
                            class="col number of orders">
                            <?= $block->escapeHtml($compatibleQuoteExtension->getQuantityOfQuoteBySubUserId($user->getSubId())) ?>
                        </td>
                    <?php endif;?>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Created Date')) ?>" class="col date">
                        <?= $block->getFormatDate($user->getCreatedAt()) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php else : ?>
    <div class="message info empty">
        <?php if ($enableQuoteExtension) : ?>
            <span><?= $block->escapeHtml(__('No record found.')) ?></span>
        <?php else :?>
            <span><?= $block->escapeHtml(__('No order found.')) ?></span>
        <?php endif;?>
    </div>
<?php endif; ?>


