<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CompanyAccount
 * @author     Extension Team
 * @copyright  Copyright (c) 2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var $block Index */

use Bss\CompanyAccount\Block\Report\Index;

$users = $block->getItems();
?>
    <div class="bss-export">
        <input id="export-btn" type="submit" value="Export CSV">
    </div>
    <div class="toolbar bottom">
        <?= $block->getChildHtml('pager') ?>
    </div>


