<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
/** @var \Bss\QuoteExtension\Block\QuoteExtension\Submit $block */
?>
<?php // @codingStandardsIgnoreFile ?>

<div id="quoteSubmit" data-bind="scope:'block-submit'" class="quote-summary">
    <div id="quote-loader" data-role="quote-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
                 alt="<?= /* @escapeNotVerified */
                 $block->escapeHtml(__('Loading...')); ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#quoteSubmit": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */
                echo $block->getJsLayout(); ?>
            },
            "*": {
                "Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
            }
        }

    </script>
    <script>
        window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Laminas\Json\Json::encode($block->getCheckoutConfig()); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
        window.isRequiredAddress = window.checkoutConfig.isRequiredAddress;
    </script>
</div>
