<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2021 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var $block \Bss\QuoteExtension\Block\QuoteExtension\View\Action */
?>
<?php // @codingStandardsIgnoreFile ?>

<?php if ($block->canShowButton("delete") && $block->isEnable()) : ?>
    <?php $action = $block->getAction('quoteextension/quote/deleteQuote/quoteId/' . $block->getRequestQuote()->getId()); ?>
    <form action="<?= /* @escapeNotVerified */ $block->escapeUrl($action); ?>" method="post" class="quote-button">
        <?php echo $block->getBlockHtml('formkey')?>
        <input type="hidden" name="request_entity_id" value="<?= /* @escapeNotVerified */ $block->getRequestQuote()->getId(); ?>">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtml(__('Delete Quote')); ?>" class="action primary quote-submit quote-move-print">
                <span><?= $block->escapeHtml(__('Delete quote')); ?></span>
            </button>
        </div>
    </form>
<?php endif; ?>
