<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_SalesRep
 * @author    Extension Team
 * @copyright Copyright (c) 2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<div class="message info empty"><span><?= $block->escapeHtml(__('Quotes grid is only available when you install our Magento 2 Request for Quote extension.')) ?></span></div>
<div class="bss_quote">
    <h4>This solution is built to fasten the quote request and management.</h4>
    <h4>For the admin</h4>
    <p>+ Enable “Add to Quote” per product or for all products</p>
    <p>+ Display “Add to Quote” for specific categories, as well</p>
    <p>+ Choose customer groups, say B2B, to allow “Add to Quote”</p>
    <p>+ Define minimum quote amount per custom group</p>
    <p>+ Manage the requests professionally: approve, reject, or customize the quote</p>
    <h4>For customers</h4>
    <p>+Add multiple products to the quote cart</p>
    <p>+Get updated on all submitted quote requests in My Quote and via emails</p>
    <p>+Convert quote to order and checkout in clicks</p>
    <h4>For sales rep</h4>
    <p>+ Access quotes submitted by the customers</p>
    <p>+ Approve, reject, or customize the quotes accordingly</p>
    <p>=>>> <a href="https://bsscommerce.com/magento-2-request-for-quote-extension.html">INSTALL NOW</a>
        to have your sales rep users connect the potential customers and seal the deals!</p>
</div>
