<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_SalesRep
 * @author    Extension Team
 * @copyright Copyright (c) 2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var Bss\SalesRep\Block\Adminhtml\Sales\Quote\SalesRep $block
 */
    $name = $block->getNameSalesRep();
?>
<tr>
    <th><?= $block->escapeHtml(__('Sales Rep')) ?></th>
    <td><span id="quote_salesrep"><?= $block->escapeHtml($name) ?></span></td>
</tr>
