<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
/** @var $block \Bss\QuoteExtension\Block\Registration */
?>
<div id="registration" data-bind="scope:'registration'">
    <br />
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#registration": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "registration": {
                            "component": "Bss_QuoteExtension/js/view/registration",
                            "config": {
                                "registrationUrl":
                                    "<?= $block->escapeJs($block->escapeUrl($block->getCreateAccountUrl())) ?>",
                                "email": "<?= $block->escapeJs($block->getEmailAddress()) ?>"
                            },
                            "children": {
                                "errors": {
                                    "component": "Magento_Ui/js/view/messages",
                                    "sortOrder": 0,
                                    "displayArea": "messages",
                                    "config": {
                                        "autoHideTimeOut": -1
                                     }
                                }
                            }
                        }
                    }
                }
            }
        }
    </script>
</div>
