<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_HidePrice
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<meta property="og:type" content="product"/>
<meta property="og:title"
      content="<?= /* @noEscape */
      $block->stripTags($block->getProduct()->getName()) ?>"/>
<meta property="og:image"
      content="<?= $block->escapeUrl($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()) ?>"/>
<meta property="og:description"
      content="<?= /* @noEscape */
      $block->stripTags($block->getProduct()->getShortDescription()) ?>"/>
<meta property="og:url" content="<?= $block->escapeUrl($block->getProduct()->getProductUrl()) ?>"/>

<?php if ($priceAmount = $block->getProduct()->getPriceInfo()
    ->getPrice(\Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE)->getAmount()) : ?>
    <?php if (empty($block->getProduct()->getHidepriceMessage())): ?>
        <meta property="product:price:amount" content="<?= $block->escapeHtmlAttr($priceAmount) ?>"/>
    <?php else: ?>
        <meta property="product:price:amount"
              content="<?= $block->escapeHtml(__($block->getProduct()->getHidepriceMessage())) ?>"/>
    <?php endif; ?>
    <?= $block->getChildHtml('meta.currency') ?>
<?php endif; ?>
