<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomerAttributes
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/**
 * @var \Bss\CustomerAttributes\Block\Adminhtml\Order\Create\Billing\Address $block
 * @var \Magento\Customer\Model\ResourceModel\Address\Collection $addressCollection
 */

$addressCollection = $block->getData('customerAddressCollection');
$finalDependentArr = [];
$dependentArr = [];
$attributeValues = [];
foreach ($block->getAddressAttribute() as $key => $value) {
    $attrId = $block->getAttributeByCode($value->getAttributeCode())->getData()[0]['attribute_id'];
    $dependentData = $block->decodeFunction($block->getAddressDependentAttribute($attrId)->getData('dependents_data'));
    if ($dependentData && count($dependentData) > 0) {
        foreach ($dependentData as $dependentDataKey => $dependentDataKeyValue):
            array_push($dependentArr, $dependentDataKeyValue['attribute-values']['dependent_attribute']['value']);
            $almostDependentArr = (array_unique($dependentArr));
        endforeach;
    }
    if (!empty($block->getAddressDependentAttribute($attrId)->getData()) && $block->getAddressDependentAttribute($attrId)->getData('dependents_data') !== 'null') {
        array_push($attributeValues, $block->getAddressDependentAttribute($attrId)->setData('attr_code', $value->getAttributeCode())->getData());
    }
}

foreach ($block->getAddressAttribute() as $key => $value) {
    if (!$value->isVisible()) {
        array_push($finalDependentArr, $key);
    }
    if ($block->isEnableCustomerAttributeDependency() == '1' && isset($almostDependentArr)) {
        foreach ($almostDependentArr as $almostKey => $almostValue):
            if ($value->getAttributeCode() === $almostValue) {
                array_push($finalDependentArr, $almostValue);
            }
        endforeach;
    }
}
$addressArray = [];
if ($block->getCustomerId()):
    $addressArray = $addressCollection->setCustomerFilter([$block->getCustomerId()])->toArray();
endif;
/**
 * @var \Magento\Sales\ViewModel\Customer\AddressFormatter $customerAddressFormatter
 */
$customerAddressFormatter = $block->getData('customerAddressFormatter');
/**
 * @var \Magento\Sales\ViewModel\Customer\Address\Billing\AddressDataProvider $billingAddressDataProvider
 */
$billingAddressDataProvider = $block->getData('billingAddressDataProvider');

/**
 * @var \Magento\Sales\Block\Adminhtml\Order\Create\Billing\Address|
 * \Magento\Sales\Block\Adminhtml\Order\Create\Shipping\Address $block
 */
if ($block->getIsShipping()):
    $_fieldsContainerId = 'order-shipping_address_fields';
    $_addressChoiceContainerId = 'order-shipping_address_choice';

    $addressCollectionJson = /* @noEscape */
        $block->getAddressCollectionJson();
    $scriptString = <<<script
    require(["Magento_Sales/order/create/form"], function(){
        order.shippingAddressContainer = '{$block->escapeJs($_fieldsContainerId)}';
        order.setAddresses({$addressCollectionJson});
    });
script;
    ?>
    <?= /* @noEscape */
    $block->renderTag('script', [], $scriptString, false) ?>
<?php
else:
    $_fieldsContainerId = 'order-billing_address_fields';
    $_addressChoiceContainerId = 'order-billing_address_choice';
    ?>
    <?php $scriptString = <<<script
        require(["Magento_Sales/order/create/form"], function(){
            order.billingAddressContainer = '{$block->escapeJs($_fieldsContainerId)}';
        });
script;
    ?>
    <?= /* @noEscape */
    $block->renderTag('script', [], $scriptString, false) ?>
<?php
endif; ?>

<fieldset class="admin__fieldset">
    <legend class="admin__legend <?= $block->escapeHtmlAttr($block->getHeaderCssClass()) ?>">
        <span><?= $block->escapeHtml($block->getHeaderText()) ?></span>
    </legend>
    <br>

    <fieldset id="<?= $block->escapeHtmlAttr($_addressChoiceContainerId) ?>"
              class="admin__fieldset order-choose-address">
        <?php if ($block->getIsShipping()): ?>
            <div class="admin__field admin__field-option admin__field-shipping-same-as-billing">
                <input type="checkbox" id="order-shipping_same_as_billing" name="shipping_same_as_billing"
                       class="admin__control-checkbox"
                       <?php if ($block->getIsAsBilling()): ?>checked<?php endif; ?> />
                <label for="order-shipping_same_as_billing" class="admin__field-label">
                    <?= $block->escapeHtml(__('Same As Billing Address')) ?>
                </label>
                <?= $block->renderEventListenerAsTag(
                    'onclick',
                    "order.setShippingAsBilling(this.checked)",
                    'input#order-shipping_same_as_billing'
                ) ?>
            </div>
        <?php endif; ?>
        <div class="admin__field admin__field-select-from-existing-address">
            <label class="admin__field-label">
                <?= $block->escapeHtml(__('Select from existing customer addresses:')) ?>
            </label>
            <?php $_id = $block->getForm()->getHtmlIdPrefix() . 'customer_address_id' ?>
            <div class="admin__field-control">
                <select id="<?= $block->escapeHtmlAttr($_id) ?>"
                        name="<?= $block->escapeHtmlAttr($block->getForm()->getHtmlNamePrefix())
                        ?>[customer_address_id]"
                        class="admin__control-select">
                    <option value=""><?= $block->escapeHtml(__('Add New Address')) ?></option>
                    <?php foreach ($addressArray as $addressId => $address): ?>
                        <option
                            value="<?= $block->escapeHtmlAttr($addressId) ?>"
                            <?php if ($addressId == $block->getAddressId()): ?> selected="selected"<?php endif; ?>>
                            <?= $block->escapeHtml($customerAddressFormatter->getAddressAsString($address)) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <?= /* @noEscape */
                $block->renderEventListenerAsTag(
                    'onchange',
                    "order.selectAddress(this, '" . $block->escapeJs($_fieldsContainerId) . "')",
                    'select#' . $block->escapeJs($_id)
                ) ?>
            </div>
        </div>
    </fieldset>

    <div class="order-address admin__fieldset" id="<?= $block->escapeHtmlAttr($_fieldsContainerId) ?>">
        <?= $block->getForm()->toHtml() ?>

        <div class="admin__field admin__field-option order-save-in-address-book">
            <input name="<?= $block->escapeHtmlAttr($block->getForm()->getHtmlNamePrefix()) ?>[save_in_address_book]"
                   type="checkbox"
                   id="<?= $block->escapeHtmlAttr($block->getForm()->getHtmlIdPrefix()) ?>save_in_address_book"
                   value="1"
                <?php if ($billingAddressDataProvider && $billingAddressDataProvider->getSaveInAddressBook() ||
                    $block->getIsShipping() && !$block->getDontSaveInAddressBook() && !$block->getAddressId()): ?>
                    checked="checked"
                <?php endif; ?>
                   class="admin__control-checkbox"/>
            <label for="<?= $block->escapeHtmlAttr($block->getForm()->getHtmlIdPrefix()) ?>save_in_address_book"
                   class="admin__field-label"><?= $block->escapeHtml(__('Add to address book')) ?></label>
        </div>
    </div>
    <?php $hideElement = 'address-' . ($block->getIsShipping() ? 'shipping' : 'billing') . '-overlay'; ?>
    <div id="<?= /* @noEscape */
    $hideElement ?>" class="order-methods-overlay">
        <span><?= $block->escapeHtml(__('You don\'t need to select a shipping address.')) ?></span>
    </div>
    <?= /* @noEscape */
    $block->renderStyleAsTag(
        "display: none;",
        'div#' . /* @noEscape */ $hideElement
    ) ?>
    <?php $scriptString = <<<script
        require(["Magento_Sales/order/create/form"], function(){
            order.bindAddressFields('{$block->escapeJs($_fieldsContainerId)}');
            order.bindAddressFields('{$block->escapeJs($_addressChoiceContainerId)}');

script;
    if ($block->getIsShipping()):
        $disable = $block->getIsAsBilling() ? 'true' : 'false';
        $scriptString .= <<<script
            order.disableShippingAddress({$disable});

script;
    endif;
    $scriptString .= <<<script
        });

script;
    ?>
    <?= /* @noEscape */
    $block->renderTag('script', [], $scriptString, false) ?>
</fieldset>
<?php if (!isset($attributeValues) || $block->isEnableCustomerAttributeDependency() == '0') {
    $attributeValues = [];
} ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Bss_CustomerAttributes/js/address":{
            "attrValues" :"<?= $block->escapeJs($block->encodeFunction($attributeValues)) ?>",
            "finalDependentArr" :"<?= $block->escapeJs($block->encodeFunction($finalDependentArr)) ?>",
            "displayValues" :"0"
            }
        }
    }
</script>
