<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Bss\QuoteExtension\Block\Adminhtml\QuoteExtension\Edit\Shipping\Method */ ?>

<div class="admin__page-section-title">
    <span class="title"><?php echo $block->getHeaderText() ?></span>
    <?php if ($block->getButtonsHtml()) : ?>
        <div class="actions"><?php echo $block->getButtonsHtml() ?></div>
    <?php endif; ?>
</div>

<?php echo $block->getChildHtml('', true) ?>
