<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/** @var $block Bss\QuoteExtension\Block\Adminhtml\QuoteExtension\Edit\SelectRate */
?>
<?php if ($block->getCustomerId()): ?>
    <tr>
        <th>
            <label class="admin__field-label" for="currency_switcher">
                <?php
                echo __('Quote Currency:') ?>
            </label>
        </th>
        <td>
            <select id="currency_switcher"
                    class="admin__control-select"
                    name="order[currency]"
                    onchange="quote.setCurrencyId(this.value);
                    quote.setCurrencySymbol(this.options[this.selectedIndex].getAttribute('symbol'));">
                <?php foreach ($block->getAvailableCurrencies() as $code): ?>
                    <option value="<?php /* @escapeNotVerified */
                    echo $code ?>"
                        <?php if ($code == $block->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>
                            symbol="<?php echo $block->getCurrencySymbol($code) ?>">
                        <?php echo $block->getCurrencyName($code) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </td>
    </tr>
<?php
endif;
