<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CompanyAccount
 * @author     Extension Team
 * @copyright  Copyright (c) 2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/**
 * @var $block Totals
 * @see \Bss\CompanyAccount\Block\Order\Totals
 */

use Bss\CompanyAccount\Block\Order\Totals;

?>
<?php foreach ($block->getTotals() as $_code => $_total) :?>
    <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
        <th <?= /* @noEscape */
        $block->getLabelProperties() ?> scope="row">
            <?php if ($_total->getStrong()) : ?>
                <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php else : ?>
                <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php endif ?>
        </th>
        <td <?= /* @noEscape */
        $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
            <?php if ($_total->getStrong()) : ?>
                <strong><?= /* @noEscape */
                    $block->formatValue($_total) ?></strong>
            <?php else : ?>
                <?= /* @noEscape */
                $block->formatValue($_total) ?>
            <?php endif ?>
        </td>
    </tr>
<?php endforeach ?>
