<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CompanyAccount
 * @author     Extension Team
 * @copyright  Copyright (c) 2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
use Bss\CompanyAccount\Block\Order\View;

?>
<?php /** @var  $block View*/?>
<div class="order-details-items ordered">
    <div class="order-title">
        <strong><?= $block->escapeHtml(__('Items Ordered')) ?></strong>
    </div>
    <?= $block->getChildHtml('bss.order.items') ?>
    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml($block->getBackTitle()) ?></span>
            </a>
        </div>
    </div>
</div>
