<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CompanyAccount
 * @author     Extension Team
 * @copyright  Copyright (c) 2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
/* @var $block \Bss\CompanyAccount\Block\Sales\Order\CreatedByCol */
?>
<td data-th="<?= $block->escapeHtml(__('Created by')) ?>" class="col created-sub-user">
    <?= $block->escapeHtml($block->getCreatedBy()) ?>
</td>
<td data-th="<?= $block->escapeHtml(__('Ship to')) ?>" class="col ship-to">
    <?= $block->escapeHtml($block->getShipTo()) ?>
</td>
