<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CompanyAccount
 * @author     Extension Team
 * @copyright  Copyright (c) 2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
/** @var $block \Bss\CompanyAccount\Block\Sales\Order\View\SubUserInfo */

$subUserInfo = $block->getSubUserInfo();

?>
<?php if (!empty($subUserInfo) && $subUserInfo['request_status'] && $subUserInfo['request_status'] == '1') : ?>
<div>
    <h3 class="page-title order-request">
        <span class="base">
            <a href="<?= $block->getViewOrderRequestUrl($subUserInfo['order_request']) ?>">
            <?= $block->escapeHtml(__('Order Request #') . $subUserInfo['order_request']) ?>
        </a>
        </span>
    </h3>
</div>
<?php endif; ?>

