<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CatalogPermission
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/**
 *  @var  $block  \Magento\Framework\View\Element\Template
 */
?>
<?php // @codingStandardsIgnoreFile ?>
<?php
$message = '';
$message = $block->getMessage();
?>
<p class="message_bss"><?php echo $block->escapeHtml(__($message)) ?></p>