<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var $block \Magento\Checkout\Block\Item\Price\Renderer */
?>
<?php // @codingStandardsIgnoreFile ?>

<?php $_item = $block->getItem() ?>
<?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
    <span class="price-wrapper price-including-tax" data-label="<?= /* @escapeNotVerified */ $block->escapeHtmlAttr(__('Incl. Tax')); ?>">
            <?php $_incl = $_item->getPriceInclTax(); ?>
            <?= /* @escapeNotVerified */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_incl) ?>
        </span>
<?php endif; ?>
<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
    <span class="price-wrapper price-excluding-tax" data-label="<?= /* @escapeNotVerified */ $block->escapeHtmlAttr(__('Excl. Tax')); ?>">
            <?= /* @escapeNotVerified */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_item->getCalculationPrice()) ?>
        </span>
<?php endif; ?>
