<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_QuoteExtension
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

/** @var \Magento\Sales\Block\Order\Email\Items\DefaultItems $block */
?>
<?php // @codingStandardsIgnoreFile ?>

<?php
/** @var \Bss\QuoteExtension\Block\QuoteExtension\Email\ViewModel\Helper $helper */
$helper = $block->getViewModel();
$item = $block->getItem();
$quote = $block->getQuote();
?>
<?php if (!$helper->canShowPrice($item, $quote)) :?>
    <span class="price"></span>
<?php else : ?>
    <?= /* @escapeNotVerified */  $helper->getModuleHelper()->formatPrice($item->getRowTotal()) ?>
<?php endif;
