<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ConfiguableGridView
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php $product = $block->getProduct();
$disableGridView = $product->getDisableGridTableView();
?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($product->isSaleable()): ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <?php if ($disableGridView || !$this->helper('Bss\ConfiguableGridView\Helper\Data')->isEnabled() || $product->getTypeId() != 'configurable') : ?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                                echo __('Qty') ?></span></label>
                        <div class="control">
                            <input type="number" name="qty" id="qty" maxlength="12"
                                   value="<?php /* @escapeNotVerified */
                                   echo $block->getProductDefaultQty() * 1 ?>" title="<?php /* @escapeNotVerified */
                            echo __('Qty') ?>" class="input-text qty"
                                   data-validate="{'required-number':true,digits:true}"/>
                            <input type="hidden"
                                   name="enable_grid_table_view"
                                   maxlength="12"
                                   value="<?php $disableGridView ?>"
                                   title="<?php /* @escapeNotVerified */
                                   echo __('Qty') ?>" class="input-text qty"
                                   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                            />
                        </div>
                    </div>
                <?php endif ?>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */
                        echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-updatecart-button">
                    <span><?php /* @escapeNotVerified */
                        echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
        "#product_addtocart_form": {
            "validation": {},
            "addToCart": {
                "cartButtonId": "#product-updatecart-button",
                "cartForm": "#product_addtocart_form"
                }
            }
        }


    </script>
<?php endif; ?>
