<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomerAttributes
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
/** @var \Bss\CustomerAttributes\Block\Adminhtml\Attribute\Edit\Tab\Attribute\Attribute $block */

$blockObj = $block->getLayout()->createBlock('Bss\CustomerAttributes\Block\Adminhtml\Attribute\Edit\Options\Options');
?>
<select name="relation_data[attribute-values][value]">
    <?php if ($blockObj->getOptionValues() === []) { ?>
        <option value="Yes">Yes</option>
        <option value="No">No</option>
    <?php } else {
        foreach ($blockObj->getOptionValues() as $key => $value) { ?>
            <option value="<?php echo $value['id']; ?>"><?php echo $value['store0']; ?></option>
        <?php }
    }
    ?>
</select>
