<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomPricing
 * @author     Extension Team
 * @copyright  Copyright (c) 2020 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

namespace Bss\CustomPricing\Block\Adminhtml\PriceRule\Edit\Tab\GeneralInformation;

use Magento\Backend\Block\Widget\Form\Generic;

/**
 * Class ContinueBtn
 *
 * @package Bss\CustomPricing\Block\Adminhtml\PriceRule\Edit\Tab\GeneralInformation
 */
class ContinueBtn extends Generic
{
    /**
     * Prepare form
     *
     * @return ContinueBtn
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    protected function _prepareForm()
    {
        $html = $this->getLayout()->createBlock(
            \Magento\Backend\Block\Widget\Button::class
        )->setData(
            [
                'label' => __('Continue'),
                'onclick' => "setSettings('" . "123123" . "', 'name', 'website_id')",
                'class' => 'save',
            ]
        );
        $addJsTemplateBlock = $this->getLayout()->createBlock(
            \Magento\Backend\Block\Template::class
        )->setTemplate("Bss_CustomPricing::price_rule/js.phtml");
        $form = $this->_formFactory->create();
        $form->addField(
            'cont_btn',
            'note',
            [
                'text' => $html->toHtml() . $addJsTemplateBlock->toHtml()
            ]
        );
        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}
